### ISSUE TITLE
Exception when tracking attributes

### ISSUE THREAD

**Issue by boyang9602** [jodavimehran/code-tracker#158]
Hi, I just tried the example in README and there's such an exception:
```
[main] INFO org.refactoringminer.util.GitServiceImpl - Cloning https://github.com/checkstyle/checkstyle.git ...
[main] INFO org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Processing tmp/checkstyle 119fd4fb33bef9f5c66fc950396669af842c21a3 ...
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String gr.uom.java.xmi.UMLAttribute.getVisibility()'
	at org.codetracker.element.Attribute.of(Attribute.java:22)
	at org.codetracker.AttributeTrackerImpl.getAttribute(AttributeTrackerImpl.java:52)
	at org.codetracker.AttributeTrackerImpl.getAttribute(AttributeTrackerImpl.java:40)
	at org.codetracker.AttributeTrackerImpl.track(AttributeTrackerImpl.java:71)
	at app.App.main(App.java:88)```

**Comment by tsantalis** [comment]
@boyang9602 
We have made some changes in the RefactoringMiner APIs
It's better to use branch https://github.com/jodavimehran/code-tracker/tree/coping-with-RMiner-changes
and build RefactoringMiner from the latest commit using command
`gradle publishToMavenLocal`

We will make soon a new release for CodeTracker that supports tracking code blocks (for, if, while, try)
