### ISSUE TITLE
NPE in CodeElementLocator.java

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#164]
https://github.com/checkstyle/checkstyle/commit/b1b49751d38af0bf2476aea1f4595283615ab7de#diff-accfc31827d56d36dbbe87ecc685803523f314e63ebd262f8207e346b60262a6R231

Checking the code element type of this block returns an NPE:

```
java.lang.NullPointerException
        at org.codetracker.util.CodeElementLocator.blockPredicate(CodeElementLocator.java:62)
        at org.codetracker.element.Method.findBlock(Method.java:77)
        at org.codetracker.util.CodeElementLocator.locate(CodeElementLocator.java:89)
        at org.CodeTrackerAPI.REST.lambda$main$1(REST.java:342)
        at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```

**Comment by tsantalis** [comment]
@flozender Fixed!
